### ISSUE TITLE
styled-components' context doesn't work

### ISSUE THREAD

**Issue by Doaa-Ismael** [toomuchdesign/next-page-tester#142]
## 💬 Questions and Help
When I wrap ```<Component />``` with a Provider ```<ThemeProvider theme={theme} >``` in _app and then try to consume this theme or provider value it returns undefined instead of the provider value.

Please help, I have been 2 days debuging to find the issue and there is no luck

home.test.jsx
```js
it('should renders home page', async () => {
    const { render} = await getPage({
         route: '/home',
          useApp: true
    });
    render();
    expect(screen.getByText('home'))
    expect(screen.getByText('child'))
});
```

_app.js

```js
import React, {useContext} from 'react';
import styled, { ThemeProvider, ThemeContext } from 'styled-components';
import ThemJson from "../theme";

const StyledContainer = styled.div`
    background-color: ${props => { 
        console.log("PROPS IN STYLED COMPONENTS", props.theme);  // output is correct
        return props.theme.color.primary;
    }
};
`
const AppChild = () => {
    const theme = useContext(ThemeContext);
    console.log(theme) // Output correct
    return (<StyledContainer>home</StyledContainer>);
};

const MyApp = ({ Component }) => {
  return (
      <ThemeProvider theme={ThemJson}>
         <AppChild />
         <Component />
    </ThemeProvider>
  );
};
export default MyApp
```

home.jsx
```js
import React, {useContext} from 'react';
import styled, {ThemeContext} from 'styled-components';

export const StyledContainer = styled.div`
    background-color: ${props => {
        console.log("PROPS IN STYLED COMPONENTS", props.theme); // ERROR can't red property theme of undefined
        return props.theme.color.primary;
    }
};
`

function Home(props) {
    const theme = useContext(ThemeContext);
    console.log(theme) // Wrong!! // theme is undefined
    return (
        <StyledContainer>
            child
        </StyledContainer>
    );
};

export default Home;
```

theme.json
```json
{
    "color": {
        "primary": "red"
    }
}
```

**Comment by Meemaw** [comment]
Hey @Doaa-Ismael 👋 

Could you try adding the following option to `getPage` call:
`nonIsolatedModules: ['styled-components']`

Let me know if that doesn't work for you

**Comment by Doaa-Ismael** [comment]
> Hey @Doaa-Ismael 👋
> 
> Could you try adding the following option to `getPage` call:
> 
> ```js
> nonIsolatedModules: ['styled-components']
> ```
> 
> Let me know if that doesn't work for you.

It didn't :( 
I tried to use wrapper option too to wrap components but it didn't work as well

**Comment by toomuchdesign** [comment]
Hi @Doaa-Ismael,
since React context relies on modules identity, you'd need to make sure that:

- `styled-components` is listed in `nonIsolatedModules` option
- your local `jest` is patched [as described in docs](https://github.com/toomuchdesign/next-page-tester#optional-patch-jest)

Please, let us know if it works. 👀

**Comment by Doaa-Ismael** [comment]
@toomuchdesign
Yes I patched jest-runtime, and I tried nonIsolatedModules option but there is no luck so far :( , 
any other suggestions?

**Comment by Meemaw** [comment]
@toomuchdesign I was just trying to make this work locally and I failed. I think its clear why the `theme` is undefined in "server" context if `styled-components` is not listed in `nonIsolatedModules` option.

However if it's listed in `nonIsolatedModules` there will be a runtime error during SSR rendering. The problem is what if we list a module inside `nonIsolatedModules` it means that module becomes a client side module and can't be "isolated". This is problematic because then it wont work correctly in "server" context due to such expressions: https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/constants.js#L15

As I see it its currently not possible to test applications that use `styled-components` at all. This is not good as this represents a big number of users.

While I don't see short term solutions to our "client" vs "server" execution context (e.g. rendering in separate processes), I think this (and probably other use cases) would be possible if we had a `ssr: boolean` option. If that option is disabled:
```js
ssr: false
```

We wouldn't do the server render + hydrate, but just do the client side rendering. I quickly tried that locally and the `styled-components` example seemed to work.

**Comment by toomuchdesign** [comment]
I get the issue now, thanks @Meemaw!
Well, this is definitely something we were waiting to show up. Let's take some time to elaborate a solution. We could definitely skip the ssr. Even though I wouldn't jump for joy :)

**Comment by Doaa-Ismael** [comment]
@Meemaw @toomuchdesign
I am new in NextJs ... could you please explain to me why ```<AppChild />``` renders correctly but ```<Component />``` don't? as both uses styled components?
 
 @Meemaw what changes I should make to skip server render + hydrate ? If it will work I can fork and use my version for now.

**Comment by toomuchdesign** [comment]
@Doaa-Ismael, as far I can see, this is not related to Next.js, but to how next-page-tester tries to emulate Next.js' server and client rendering (without a server).

**Comment by toomuchdesign** [comment]
@Meemaw I'd like to try and see how far we can get by gathering all the initial ssr operations in a single go. Which also means getting rid of simultaneous client/server version of required files.

Can you see any sense in this approach? Could it mitigate this issue?

**Comment by Meemaw** [comment]
@toomuchdesign I'm not sure such approach would solve this issue. Because we are in 1 process trying to emulate 2 processes we are facing the multiple React instances error. We mitigated that by introducing `nonIsolatedModules`, but that means those modules are tied to the "client" context and can't be used in "server" context if they are doing some module level `isServer` checks and executing logic based on that.

I think we would still face the same problem even if we did whole server flow separately in one go. I might be wrong and perhaps you have some idea to make it work.

**Comment by toomuchdesign** [comment]
@Meemaw I'm not sure neither, but I can't see how ssr context could blow up if we were able to render in "server" mode in a single go and return a string, immediately. Once we have the string we only have to deal with client env, haven't we? 🤔

**Comment by Meemaw** [comment]
If I understand our approach correctly it will blow up if we list `styled-components`  in `nonIsolatedModules` (binding it to a current context). If we don't do that the `Context` wont work correctly and will be undefined at runtime.

**Comment by Meemaw** [comment]
@toomuchdesign  in case these changes don't work, I still think it's worth the effort. Those changes would enable:
- simplify code
- supper easy way to turn `ssr` for performance reasons (I would like to see some benchmarks on the difference it makes, but I expect it would be significant for large projects with many tests)
- super easy to implement SSR rendering in a separate process (if we decide to do so)

**Comment by toomuchdesign** [comment]
>  If we don't do that the Context wont work correctly and will be undefined at runtime.

I'm trying to find out what could blow up. I'm considering the option of ssr'ing in a single go in the same process as we do now, and maybe getting rid of `nonIsolatedModules`.

I agree the project could benefit from such an approach: doubled imported files were super funny to see in action but I admit they are a nasty workaround :)

**Comment by toomuchdesign** [comment]
Hi @Doaa-Ismael,
we've just released v0.20.0 which should address the issue you described.
Would you mind updating and give us feedback? Thanks!

**Comment by neighlyd-alo** [comment]
I upgraded to v0.20.0 and am still encountering the same issue. The moment I use any styles through styled-components, the tests break with an error message. This is regardless of whether I wrap them in a theme wrapper or not. This happens with both patched and unpatched jest.

```bash
# Error message
    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined

       8 |       nonIsolatedModules: ['styled-components']
       9 |     })
    > 10 |     render()
         |     ^
      11 |     // expect(screen.getByText('hi')).toBeInTheDocument()
      12 |   })
      13 | })

      at V (node_modules/styled-components/src/constants.js:4:33)
      at new names (node_modules/styled-components/src/constants.js:4:33)
      at e.id [as getTag] (node_modules/styled-components/src/sheet/Sheet.js:44:11)
      at e.t.insertRules (node_modules/styled-components/src/sheet/Sheet.js:97:31)
      at e.id [as generateAndInjectStyles] (node_modules/styled-components/src/utils/isStaticRules.js:6:54)
      at id (node_modules/styled-components/src/models/Keyframes.js:20:51)
      at id (node_modules/styled-components/src/models/Keyframes.js:20:51)
      at Object.pages__H1 [as render] (node_modules/styled-components/src/models/Keyframes.js:20:51)
      at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:3872:44)
      at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
      at Object.renderToString (node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
      at node_modules/next-page-tester/dist/makeRenderMethods.js:16:75
      at Object.executeAsIfOnServerSync (node_modules/next-page-tester/dist/server.js:39:16)
      at serverRenderToString (node_modules/next-page-tester/dist/makeRenderMethods.js:16:28)
      at serverRender (node_modules/next-page-tester/dist/makeRenderMethods.js:21:26)
      at render (node_modules/next-page-tester/dist/makeRenderMethods.js:39:30)
      at Object.<anonymous> (__tests__/Home.test.js:10:5)
```

For example:

```javascript
/* pages/index.js */
// Passing
import styled from 'styled-components'
const H1 = styled('h1')``

// Failing
import styled from 'styled-components'
const H1 = styled('h1')`
  color: blue;
`
```

**Comment by toomuchdesign** [comment]
Hi @neighlyd-alo, thanks for reporting, would mind setting up a reproduction repository?

**Comment by jefferson-william** [comment]
I have a repository with this exact problem.

https://github.com/jefferson-william/next-boilerplate/issues/1#issue-812913650

![image](https://user-images.githubusercontent.com/2935122/108634050-80b09e00-7456-11eb-9245-34ef37b1bb7a.png)

**Comment by toomuchdesign** [comment]
v0.21.0 has been published. @Doaa-Ismael is this issue still relevant?

**Comment by toomuchdesign** [comment]
@jefferson-william is this issue still relevant?

**Comment by ThePicoNerd** [comment]
> I have a repository with this exact problem.
> 
> [jefferson-william/next-boilerplate#1 (comment)](https://github.com/jefferson-william/next-boilerplate/issues/1#issue-812913650)
> 
> ![image](https://user-images.githubusercontent.com/2935122/108634050-80b09e00-7456-11eb-9245-34ef37b1bb7a.png)

Using Emotion, I get the same output.

**Comment by Meemaw** [comment]
@ThePicoNerd I have a feeling you need to [patch-jest](https://github.com/toomuchdesign/next-page-tester/#optional-patch-jest); or have you done that already?

**Comment by ThePicoNerd** [comment]
Should have read the docs ... 🤦 Sorry for taking up your time and thank you for an amazing package, not to mention the fast response!
